# ============================================================
# WireGuardVPN - Networks
# ============================================================
#
# NAME          CIDR                VIA
#
LAN_UIO         192.168.2.0/24      eno1
BROADCAST_6     192.168.6.0/24      enp7s0
CORP_28         192.168.28.0/24     eno1
