# ============================================================
# WireGuardVPN - Service Catalog
# ============================================================
#
# NAME                  DESTINATION         PROTOCOL    PORTS
#

DNS_INTERNAL            192.168.2.10        udp         53
DNS_INTERNAL_TCP        192.168.2.10        tcp         53

MEDIAMTX_WEBRTC         192.168.2.168       tcp         8889
MEDIAMTX_ICE_UDP        192.168.2.168       udp         8189
MEDIAMTX_ICE_TCP        192.168.2.168       tcp         8189
MEDIAMTX_RTSP           192.168.2.168       tcp         8554
MEDIAMTX_HLS            192.168.2.168       tcp         8787

FONOS_PORTAL            192.168.2.168       tcp         9443

ASTERISK_SIP_UDP        192.168.2.168       udp         5060
ASTERISK_SIP_TCP        192.168.2.168       tcp         5060
ASTERISK_RTP            192.168.2.168       udp         10000:10100
