ROLE=fonos

SERVER_ACCESS=no
DNS_ACCESS=yes

SERVICES="
MEDIAMTX_WEBRTC
MEDIAMTX_ICE_UDP
MEDIAMTX_ICE_TCP
FONOS_PORTAL
ASTERISK_SIP_UDP
ASTERISK_SIP_TCP
ASTERISK_RTP
"

NETWORKS=

ALLOWED_IPS="10.8.0.0/24,192.168.2.168/32,192.168.2.10/32"
